### ISSUE TITLE
SocketException

### ISSUE THREAD

**Issue by mazuryv** [zkteco-home/redis-windows#11]
Thank you about sentinel, but I have another issue:
When I try to connect to Redis, SocketException is thrown. Redis service is stopped.
redis.windows-service.conf
````
port 6379

loglevel notice
logfile "Logs/redis_log.txt"

slave-serve-stale-data yes
slave-read-only yes

repl-diskless-sync no
repl-diskless-sync-delay 5
repl-disable-tcp-nodelay no

maxmemory 256mb
appendonly no
maxmemory-policy allkeys-lru
````
Application error in Event Viewer
```
Faulting application name: redis-server.exe, version: 7.0.0.0, time stamp: 0x621adc90
Faulting module name: redis-server.exe, version: 7.0.0.0, time stamp: 0x621adc90
Exception code: 0xc0000005
Fault offset: 0x000000000007b578
Faulting process id: 0x5040
Faulting application start time: 0x01d82c9f89ec08e7
Faulting application path: C:\Redis\redis-server.exe
Faulting module path: C:\Redis\redis-server.exe
Report Id: 6818c6c1-176e-40da-aa21-22a02f4c6484
Faulting package full name: 
Faulting package-relative application ID: 
```
```
Fault bucket 2092848452791133116, type 4
Event Name: APPCRASH
Response: Not available
Cab Id: 0

Problem signature:
P1: redis-server.exe
P2: 7.0.0.0
P3: 621adc90
P4: redis-server.exe
P5: 7.0.0.0
P6: 621adc90
P7: c0000005
P8: 000000000007b578
P9: 
P10: 

Attached files:
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER728B.tmp.dmp
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER7328.tmp.WERInternalMetadata.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER7338.tmp.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER733A.tmp.csv
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER736A.tmp.txt

These files may be available here:
\\?\C:\ProgramData\Microsoft\Windows\WER\ReportArchive\AppCrash_redis-server.exe_c749f1588964366085baee65654c61d83964911_d8653adc_dd74f9f3-c5b9-4110-a534-34aef3f71470

Analysis symbol: 
Rechecking for solution: 0
Report Id: 6818c6c1-176e-40da-aa21-22a02f4c6484
Report Status: 268435456
Hashed bucket: eb7f41269b79617fcd0b4a94555763bc

```
![image](https://user-images.githubusercontent.com/26767342/155984794-fd5600d9-3cf1-4efe-9e39-a7e2b4893608.png)

My code uses StackExchange.Redis
`var connection =ConnectionMultiplexer.Connect("localhost");`
Thank you in advance.

**Comment by mazuryv** [comment]
My code is connecting well with version redis-windows-6.2.6.4, but sentinel is not working at all.

**Comment by zkteco-home** [comment]
![image](https://user-images.githubusercontent.com/66519168/156096135-3715153e-44d4-4a13-9984-1132f5919df5.png)
in fact,i tested it via redis tools,python and java,it work fine

**Comment by zkteco-home** [comment]
you can pull  and test it again

**Comment by zkteco-home** [comment]
can you send your test demo  to me?i want to use it to test. i used some third part tools to test,it also work fine

**Comment by zkteco-home** [comment]
> My code is connecting well with version redis-windows-6.2.6.4, but sentinel is not working at all.

6.2.6.4 is OK，it's so weird,connect code is as same as before

**Comment by mazuryv** [comment]
Hello.
redis-cli.exe works as expected. Another Redis Desktop Manager - works too. My application is a part big web solution. I try to prepare test demo.
I found that error thrown in my asp.net 5.0 0application
```
services.AddStackExchangeRedisCache(o =>
            {
                o.Configuration = redisConnectionString;
            });
```
And additional:
Logs do not work:
```
port 6379

loglevel debug 
logfile "Logs/redis_log.txt"
```
In 6.2.6.4  logs work as expected.

**Comment by mazuryv** [comment]
Super!!! It has helped! I start to testing all parts. Thank you very much!!!
