### ISSUE TITLE
Logs do not work

### ISSUE THREAD

**Issue by mazuryv** [zkteco-home/redis-windows#14]
Logs do not work:
```
port 6379

loglevel debug 
logfile "Logs/redis_log.txt"
```
In 6.2.6.4  logs work as expected.

**Comment by zkteco-home** [comment]
![image](https://user-images.githubusercontent.com/66519168/156768234-d62d727f-da74-4317-8279-67c0dcc43a99.png)
please comment logfile here,logs can work.later i will change code and support it.

**Comment by zkteco-home** [comment]
hi,how is your testing result?

**Comment by mazuryv** [comment]
```
port 6379

loglevel debug 
logfile "Logs/redis_log.txt"
```
Logs don`t work anyway.

**Comment by zkteco-home** [comment]
![image](https://user-images.githubusercontent.com/66519168/158524397-4dda397d-a773-4a69-bf95-8affa3f5ddb3.png)
i tested it,logs work fine.

**Comment by mazuryv** [comment]
Ok. From cmd it works fine, but if service was installed - only file was created, but this file is always empty

**Comment by zkteco-home** [comment]
Thanks,i knew reason,i will update it on Mar 20.

**Comment by mazuryv** [comment]
Thank you. Logs is working now
