### ISSUE TITLE
Please correct some misleading information in this repo

### ISSUE THREAD

**Issue by yossigo** [zkteco-home/redis-windows#15]
The binaries provided here are not an official Redis port to Windows, and should not be presented as such.
Also, Redis 7.0 was not released yet so at best this port is based on a release candidate.

**Comment by zkteco-home** [comment]
> The binaries provided here are not an official Redis port to Windows, and should not be presented as such. Also, Redis 7.0 was not released yet so at best this port is based on a release candidate.

ok,thanks,i will correct it on 13 March.

**Comment by zkteco-home** [comment]
I've spent a lot of time working on the windows edition and if people don't like it I'll close the project in the future
