### ISSUE TITLE
Range index is wrong.

### ISSUE THREAD

**Issue by HoytRen** [zkteco-home/redis-windows#2]
redis_version:6.2.6
According to https://redis.io/commands/zrange,
Command: zrange XXX 0 -1 should return all members in that zSet, but it currently return only 1 member.
I tried the cli and Lettuce(java), both interfaces have this problem.

**Comment by zkteco-home** [comment]
thank you,i will check it and fix it

**Comment by zkteco-home** [comment]
I fixed this issue,please check it and give me feedback,thanks

**Comment by HoytRen** [comment]
Thanks for the quick fix. -1 is working now.
Here is still problem about the index.
zrange test 0 (1
produce an error, but it shoud return the first member.

**Comment by zkteco-home** [comment]
i use this command to test it,  ZRANGE myset 0 0 ,it is ok,please tell your command details,thanks

**Comment by HoytRen** [comment]
Let me explain:
zrange test 0 (1
and
zrange test 0 1
are different. Here isn't typo. You could notice here is a '('.
when zrange test 0 1 return the first and second members,
the zrange test 0 (1 return only the first member.

**Comment by HoytRen** [comment]
zrange test 0 (1
and
zrange test 0 0
should have same results, but it doesn't work currently.

**Comment by zkteco-home** [comment]
sorry ,maybe i didnt understand,when i use zrange test 0 (1, it  doesnt work,it means not support this kind of parameter,
![image](https://user-images.githubusercontent.com/66519168/146976602-6520d89e-507b-4fbd-b341-91b7c10c2260.png)

**Comment by zkteco-home** [comment]
ok,i will continue to check,your command is zrange test 0 (1 BYSCORE

**Comment by zkteco-home** [comment]
> Let me explain: zrange test 0 (1 and zrange test 0 1 are different. Here isn't typo. You could notice here is a '('. when zrange test 0 1 return the first and second members, the zrange test 0 (1 return only the first member.

i fixed this issue and commited,please check again,thanks

**Comment by HoytRen** [comment]
I replaced the redis binary, checked the timestamp of the files and restarted computer.
It seems something wrong, and the zrange test 0 (1 still produce a error:
127.0.0.1:6379> zadd test 1 a 2 b 3 c
(integer) 3
127.0.0.1:6379> zrange test 0 (1
(error) ERR value is not an integer or out of range
127.0.0.1:6379>

**Comment by zkteco-home** [comment]
> I replaced the redis binary, checked the timestamp of the files and restarted computer. It seems something wrong, and the zrange test 0 (1 still produce a error: 127.0.0.1:6379> zadd test 1 a 2 b 3 c (integer) 3 127.0.0.1:6379> zrange test 0 (1 (error) ERR value is not an integer or out of range 127.0.0.1:6379>

this is my test result

> I replaced the redis binary, checked the timestamp of the files and restarted computer. It seems something wrong, and the zrange test 0 (1 still produce a error: 127.0.0.1:6379> zadd test 1 a 2 b 3 c (integer) 3 127.0.0.1:6379> zrange test 0 (1 (error) ERR value is not an integer or out of range 127.0.0.1:6379>

this is my test screenshot

**Comment by zkteco-home** [comment]
> I replaced the redis binary, checked the timestamp of the files and restarted computer. It seems something wrong, and the zrange test 0 (1 still produce a error: 127.0.0.1:6379> zadd test 1 a 2 b 3 c (integer) 3 127.0.0.1:6379> zrange test 0 (1 (error) ERR value is not an integer or out of range 127.0.0.1:6379>

![image](https://user-images.githubusercontent.com/66519168/147201483-c0b79712-0bfa-4c32-8da3-d57e484fff1f.png)
this is my test screenshot

**Comment by zkteco-home** [comment]
![image](https://user-images.githubusercontent.com/66519168/147204692-87b675f0-e4d9-45c7-9d47-ba571b56a99a.png)

**Comment by zkteco-home** [comment]
![image](https://user-images.githubusercontent.com/66519168/147207534-59199f71-d861-4a82-b6ae-36e4a1e56a3e.png)

**Comment by HoytRen** [comment]
Sorry, I made mistake and you are right. "(" is a feature of zrangebyscore or 'zrange XXX X X byscore' but not for zrange. I confirm the redis works all right and this issue is resolved now. Thank you again.
