### ISSUE TITLE
Log File breaks Service

### ISSUE THREAD

**Issue by Raeas2007** [zkteco-home/redis-windows#21]
If the configuration entry in the conf file has the word "Redis" in it for "logfile" (for instance, I used both logfile C:/Logs/redis.txt and logfile C:/Logs/Redis/logs.txt), then the command redis-server --service-start will fail with the message: "Redis service failed to start." and nothing logged to the log file (obviously) or event viewer related to the error.  However, by changing the entry to logfile C:/Logs/red_is.txt, the service starts without issue.

**Comment by zkteco-home** [comment]
Thanks for your feedback,i will fix this issue in the next edition,now you void to use redis temporarily.

**Comment by zkteco-home** [comment]
according to your logfile name,i tested it,it looks working fine.  attention:you firstly need to create log folder manually
![image](https://user-images.githubusercontent.com/66519168/170681305-2025dcf5-0e04-4d5c-9dab-e9a5ee175528.png)
