### ISSUE TITLE
Problem setting up the server on SSL

### ISSUE THREAD

**Issue by tomjawo** [zkteco-home/redis-windows#25]
Hi! I'm having issues setting up the server with "tls-port" parameter enabled.
If I uncomment that particular line in the config file I get a config parsing error:

*** FATAL CONFIG FILE ERROR ***
[003084] 11 Jul 08:08:07.529 # Reading the configuration file, at line 183
[003084] 11 Jul 08:08:07.530 # >>> 'tls-port 6379'
[003084] 11 Jul 08:08:07.531 # Bad directive or wrong number of arguments

Any ideas on that ?

**Comment by zkteco-home** [comment]
i guess you pulled from master.please pull branch Redis7.0-openssl1.1.1 and try to test.next time send your conf here

**Comment by pspad** [comment]
I   pull code from  branch Redis7.0-openssl1.1.1,and try to start from command line:
redis-server --tls-port 6380 --port 0 --tls-cert-file cert\redis.crt  --tls-key-file cert\redis.key --tls-ca-cert-file cert\ca.crt

Then got the same error message :
Invalid argument during startup: unknown argument: tls-port

This command can startup redis server normally from program I compiled   using MSYS on windows.

**Comment by zkteco-home** [comment]
try to use confi file to set up ssl params

**Comment by zkteco-home** [comment]
Fixed unknown argument: tls-port and commited to branch Redis7.0-openssl1.1.1,please pull and test it,it there is issue and let me know.Thanks

**Comment by pspad** [comment]
my redis.conf :

################################# TLS/SSL conf#################################


 port 0
 tls-port 6380


 tls-cert-file cert\redis.crt
 tls-key-file cert\redis.key
 tls-ca-cert-file cert\ca.crt
 tls-protocols "TLSv1.2 TLSv1.3"
 tls-auth-clients no
################################# FINISH #####################################

When I connect from redis-cli:
![image](https://user-images.githubusercontent.com/46801137/200753507-ad2a154a-fb4f-4e8d-af28-c051126ee5b5.png)


Got error,cannot connect :
![image](https://user-images.githubusercontent.com/46801137/200751742-147a1d81-e1dd-4518-86a1-5dff86c165df.png)
Thank you!
