### ISSUE TITLE
listen: Unknown error

### ISSUE THREAD

**Issue by owllyi** [zkteco-home/redis-windows#26]
[030812] 04 Aug 18:00:47.789 # RedisWin is starting ......
[030812] 04 Aug 18:00:47.789 # RedisWin version=7.0.4, bits=64, commit=07/20/2022, modified=0, pid=30812, just started
[030812] 04 Aug 18:00:47.790 # Configuration loaded
[030812] 04 Aug 18:00:47.793 * monotonic clock: POSIX clock_gettime
[030812] 04 Aug 18:00:47.795 # Warning: Could not create server TCP listening socket ::1:6379: listen: Unknown error
[030812] 04 Aug 18:00:47.795 # Failed listening on port 6379 (TCP), aborting.

System is Win10 X64，Help please, Thanks~~~

**Comment by zkteco-home** [comment]
please try to change port and test it

**Comment by zkteco-home** [comment]
any update?

**Comment by owllyi** [comment]
use 16397, not work~

**Comment by zkteco-home** [comment]
you send me more detail,how did you start redis?what is your config file?this issue looks port is occupied

**Comment by zkteco-home** [comment]
refer to  https://github.com/tporadowski/redis/issues/88#issuecomment-963507349  

try to change bind 127.0.0.1 -::1  to bind 0.0.0.0 -::1

**Comment by Ostrich5yw** [comment]
![image](https://user-images.githubusercontent.com/72113963/184567830-1c343824-effd-4767-9f42-f3e611333a63.png)
Windows11 also experienced this problem, with port 6379 not being used

**Comment by zkteco-home** [comment]
my environment is under Windows 11,we recommand  redis-server.exe redis.conf 

![image](https://user-images.githubusercontent.com/66519168/184603581-1616ffb2-bfb5-4f30-a071-20d89f688687.png)

**Comment by ldmzw** [comment]
遇到同样的问题
修改 bind 127.0.0.1 ::1 为 bind 127.0.0.1 后启动成功

**Comment by andywu188** [comment]
> 遇到同样的问题 修改 bind 127.0.0.1 ：：1 为 bind 127.0.0.1 后启动成功

2008 R2上同样问题，按你的方案解决，WIN10上却没问题，真搞不懂。

**Comment by zkteco-home** [comment]
I tested it on Windows 2008 R2, it works fine for bind 127.0.0.1 or bind 127.0.0.1 ::1

**Comment by andywu188** [comment]
![image](https://user-images.githubusercontent.com/31318039/187170253-a3d7b800-1f90-4700-84d5-c19baef09943.png)

**Comment by zkteco-home** [comment]
Thanks
