### ISSUE TITLE
Redis Bug Report

### ISSUE THREAD

**Issue by kabapy** [zkteco-home/redis-windows#28]
=== REDIS BUG REPORT START: Cut & paste starting from here ===
[002588] 19 Aug 21:26:45.831 # --- EXCEPTION_ACCESS_VIOLATION
[002588] 19 Aug 21:26:45.836 # --- STACK TRACE
redis-server.exe!((null):0)(0x1401E2B40, 0x0014FF60, 0x1401197F0, 0x0014DF40)
redis-server.exe!((null):0)(0x0014DF40, 0x140119701, 0x00000000, 0x00000000)
KERNELBASE.dll!UnhandledExceptionFilter((null):0)(0x0014DFF0, 0x7FFDB0C37654, 0x00000000, 0x0014DF88)
ntdll.dll!memset((null):0)(0x7FFDB0C64A24, 0x7FFDB0AF0000, 0x0014DFF0, 0x7FFDB0B20E7B)
ntdll.dll!_C_specific_handler((null):0)(0x00000000, 0x0014E4F0, 0x0014EBB0, 0x00000000)
ntdll.dll!_chkstk((null):0)(0x00000000, 0x0014E4F0, 0x0014EBB0, 0x00000000)
ntdll.dll!RtlRaiseException((null):0)(0x06800008, 0x1400D9073, 0x7FE146801C00, 0x05011200)
ntdll.dll!KiUserExceptionDispatcher((null):0)(0x7FE146801C00, 0x7FE13B400A42, 0x06400100, 0x7FE13B400A18)
redis-server.exe!KiUserExceptionDispatcher((null):0)(0x7FE146801C00, 0x7FE13B400A20, 0x7FE13B400A18, 0x7FE13B400A30)
redis-server.exe!KiUserExceptionDispatcher((null):0)(0x7FE13B400A10, 0x000000FF, 0x000000EF, 0x7FE139401403)
redis-server.exe!KiUserExceptionDispatcher((null):0)(0x7FE139405303, 0x18200000000, 0x7FE13B400A10, 0x00000000)
redis-server.exe!KiUserExceptionDispatcher((null):0)(0x0014F0E0, 0x08400000, 0x0014F140, 0x0014F1E0)
redis-server.exe!KiUserExceptionDispatcher((null):0)(0x7FE13D82C540, 0x0014F140, 0x0014F140, 0x08400000)
redis-server.exe!KiUserExceptionDispatcher((null):0)(0x00000000, 0x00000000, 0x00000000, 0x00000000)
redis-server.exe!KiUserExceptionDispatcher((null):0)(0x03F3DAA0, 0x02850000, 0x00000000, 0x03F3DAA0)
redis-server.exe!KiUserExceptionDispatcher((null):0)(0x02850000, 0x02850000, 0x00000000, 0x00000270)
redis-server.exe!KiUserExceptionDispatcher((null):0)(0x0000025C, 0x00000000, 0x0000025C, 0x2AAAAAAAAAAAAAAB)
redis-server.exe!KiUserExceptionDispatcher((null):0)(0x00000000, 0x00000000, 0x0056A4A0, 0x00000000)
redis-server.exe!KiUserExceptionDispatcher((null):0)(0x00000000, 0x00000000, 0x00000000, 0x00000000)
KERNEL32.DLL!BaseThreadInitThunk((null):0)(0x00000000, 0x00000000, 0x00000000, 0x00000000)
ntdll.dll!RtlUserThreadStart((null):0)(0x00000000, 0x00000000, 0x00000000, 0x00000000)
ntdll.dll!RtlUserThreadStart((null):0)(0x00000000, 0x00000000, 0x00000000, 0x00000000)
[002588] 19 Aug 21:26:45.869 #
=== REDIS BUG REPORT END. Make sure to include from START to END. ===

**Comment by zkteco-home** [comment]
I hope you can provide more details,ony error message,i dont know how to reproduce error.

**Comment by zkteco-home** [comment]
perhaps i fixed this bug,please test it and let me know result, pull from branch redis-bug-28

thanks very much
