### ISSUE TITLE
"install_redis.cmd" does fail when path has blanks

### ISSUE THREAD

**Issue by UweKeim** [zkteco-home/redis-windows#3]
When starting "install_redis.cmd" from e.g.

> "C:\Program Files\redis"

The service installs but fails to start.

I did not investigate further, but instead put redis into a path without blanks, e.g.

> "C:\redis"

**Comment by zkteco-home** [comment]
thank you very much for your issue,i fixed that and commited.

**Comment by UweKeim** [comment]
Awesome, thank you very much 😊
