### ISSUE TITLE
用可视化工具读取不到数据

### ISSUE THREAD

**Issue by izhangguapi** [zkteco-home/redis-windows#37]
The data is not displayed with the visualization tool, but can be queried with the command line

![image](https://user-images.githubusercontent.com/33612298/213878083-205b9df7-3f7b-431c-a325-e013fc10a07a.png)

![image](https://user-images.githubusercontent.com/33612298/213878120-d2528dae-b400-4208-94c2-e1ce628f980f.png)

**Comment by zkteco-home** [comment]
![image](https://user-images.githubusercontent.com/66519168/213963947-b66bfc64-8707-4436-8742-01c0dae4fb79.png)
i can get data with other tools,i dont know your tool

**Comment by zkteco-home** [comment]
thanks for  your report,i will check it.

**Comment by zkteco-home** [comment]
Fixed this bcz of scan command issue(long to long long)

**Comment by izhangguapi** [comment]
Thank you very much for your help
