### ISSUE TITLE
win10以服务方式运行，停止服务时不保存rdb文件

### ISSUE THREAD

**Issue by sds0917** [zkteco-home/redis-windows#38]
win10以服务方式运行，停止服务时不保存rdb文件。
如果以命令行方式运行，关闭命令行窗口时可以正常保存rdb文件。

安装服务的命令来自于README.md文件，版本为7.0.8.1

感谢

**Comment by zkteco-home** [comment]
I will investigate,thanks

**Comment by zkteco-home** [comment]
i tested it on windows 11,it looks working fine,you check if you use same config file when command line or service.
![image](https://user-images.githubusercontent.com/66519168/215317244-0f616756-a43a-410e-9700-4d588f6bf9c8.png)
