### ISSUE TITLE
Pubsub messages are unordered

### ISSUE THREAD

**Issue by huyhu** [zkteco-home/redis-windows#4]
Pubsub messages are unordered even though they are sent sequentially on the subscriber side they came in a mixed order. The same does not happen with Redis on docker.

**Comment by zkteco-home** [comment]
i will try to fix it ASAP,thanks

**Comment by zkteco-home** [comment]
can you give me more details for this issue?

**Comment by huyhu** [comment]
Hey, thanks for the quick response! I was just checking if the repo is alive. In the meantime, I was able to get it fixed. The trick is using the sequential subscribe.

https://stackexchange.github.io/StackExchange.Redis/PubSubOrder

BTW, do you have the source code of how you build Redis for windows?
