### ISSUE TITLE
Needs in your little help with file versions.

### ISSUE THREAD

**Issue by dmitriy-bredun** [zkteco-home/redis-windows#40]
Hello gentlemens, 

A lot of thanks for your work and supporting the tool! I also find your product very helpful!

I just have one small request.

I have noticed that several *.exe files (listed below) have version 7.0.0.0 on the "Details" tab in the file's properties.
redis-benchmark.exe   
redis-check-aof.exe
redis-check-rdb.exe
redis-cli.exe
redis-server.exe
 

Is it correct behaviour? 

if not...  would you kindly change the file versions for 7.0.7 and 7.0.8 releases to avoid misunderstandings in the future.

![изображение](https://user-images.githubusercontent.com/25133827/220128061-53be7643-0c2a-475f-bd6f-0bb1c934a73b.png)

**Comment by zkteco-home** [comment]
Thanks,i will change it next Sunday
