### ISSUE TITLE
RediSearch

### ISSUE THREAD

**Issue by M0nk3yOo** [zkteco-home/redis-windows#41]
Hi,

first of all: many thanks for your work!!!! I'm always looking for an updated REDIS-server version for Windows.

One short question: do you expect to bring also the RediSearch module for Windows? If so, is there any timeline?

Thanks
Best

**Comment by zkteco-home** [comment]
I tried to compile it and failed,it's so complicated.

**Comment by tcrch** [comment]
would love to see this come to redis-windows👍

**Comment by ladrians** [comment]
+1 to this questions. There is an option to use RediSearch so store embeddings and then search for closest matches, which would be very useful for example to use from openAI, I was following [these instructions](https://github.com/openai/openai-cookbook/blob/main/examples/vector_databases/Using_vector_databases_for_embeddings_search.ipynb).

**Comment by dengyakui** [comment]
+1

**Comment by samloba** [comment]
Thx for this very helpfull job. is there a way to sponsor redisSearch module port to windows?

**Comment by zkteco-home** [comment]
i am trying to do that,but it looks difficulty to compile

**Comment by samloba** [comment]
ok keep trying; you will do it!!!👍
