### ISSUE TITLE
redis-windows bug-report

### ISSUE THREAD

**Issue by 1070328137** [zkteco-home/redis-windows#47]
helllo ,i used redis-7.0.11-windows  ,it often crashed , The frequency of persistent hard drives is a little high,

save 300 1
 save 100 10
 save 60 100

redislog:

=== REDIS BUG REPORT START: Cut & paste starting from here ===
[001008] 31 May 02:24:32.224 # --- ABORT
[001008] 31 May 02:24:32.224 # --- STACK TRACE
redis-server.exe!((null):0)(0x00000016, 0x7FCE1E800E00, 0x140122550, 0x14025B550)
redis-server.exe!((null):0)(0x14025B550, 0x140141DA7, 0x0013E888, 0x0013E870)
redis-server.exe!((null):0)(0x0013E801, 0x00000000, 0x00000000, 0x00000C02)
redis-server.exe!((null):0)(0x001300A0, 0x140214160, 0x00000C02, 0x00000051)
redis-server.exe!((null):0)(0x00000C05, 0x00000C05, 0x0013EDA0, 0x0013ECA0)
redis-server.exe!((null):0)(0x00000C05, 0x0013EDA0, 0x0013EDA0, 0x11800000)
redis-server.exe!((null):0)(0x00000C05, 0x7FCE1E800E00, 0x0013EDA0, 0x0013EDA0)
redis-server.exe!((null):0)(0x001C7440, 0x140153FE2, 0x00000000, 0x7FCE079674C0)
redis-server.exe!((null):0)(0x0013EDA0, 0x00000010, 0x7FCE07E4B404, 0x0013EDA0)
redis-server.exe!((null):0)(0x7FCE07E4B3D1, 0x05400000, 0x00000322, 0x05400000)
redis-server.exe!((null):0)(0x00000000, 0x00000000, 0x00000000, 0x00000000)
redis-server.exe!((null):0)(0x001C7440, 0x00000000, 0x00000000, 0x00000004)
redis-server.exe!((null):0)(0x00160CC0, 0x00000000, 0x1401DE600, 0x000003F0)
redis-server.exe!((null):0)(0xFFFFFFFFFFFFFFFF, 0x11000514, 0x00000000, 0x0000011C)
redis-server.exe!((null):0)(0x00000154, 0x00000006, 0x00000154, 0x2AAAAAAAAAAAAAAB)
redis-server.exe!((null):0)(0x140128000, 0x140128055, 0x001C79A0, 0x7FF5FFFFE000)
redis-server.exe!((null):0)(0x14012804C, 0x7FF5FFFFE000, 0x00000000, 0x00000000)
KERNEL32.DLL!BaseThreadInitThunk((null):0)(0x7FFF188813F0, 0x00000000, 0x00000000, 0x00000000)
ntdll.dll!RtlUserThreadStart((null):0)(0x00000000, 0x00000000, 0x00000000, 0x00000000)
ntdll.dll!RtlUserThreadStart((null):0)(0x00000000, 0x00000000, 0x00000000, 0x00000000)
[001008] 31 May 02:24:32.224 # 
=== REDIS BUG REPORT END. Make sure to include from START to END. ===

**Comment by zkteco-home** [comment]
try to use redis-benchmark.exe to test it,
I also use Save 1 1  ,it still work fine.
redis-benchmark.exe -p 6379 -a password

**Comment by zkteco-home** [comment]
7.2.0 fixed it
