### ISSUE TITLE
Running redis-server with TLS

### ISSUE THREAD

**Issue by zsharon75** [zkteco-home/redis-windows#54]
Hi,

Trying to configure TLS seem to cause service not to start properly - 
Can you please check Redis-Server is built with BUILD_TLS flag turned on?
(see https://redis.io/docs/management/security/encryption/)

And provide config sample in Readme on how to operate it?

Thanks,

Zachi Sharon.

**Comment by zkteco-home** [comment]
sorry,this standard version does not support TLS.

**Comment by zsharon75** [comment]
Can you please guide us how you build from redis open-source this Redis-server?

**Comment by zkteco-home** [comment]
would you like to sponsor this project?

**Comment by zsharon75** [comment]
Sponsor - or development contributor?
I wish to assist adding TLS support -
I have C/C++ Skills - just need access to the source code & working env to
compile it.

Thanks,
Zachi
