### ISSUE TITLE
Redis stopped when it crashed

### ISSUE THREAD

**Issue by vladceresna** [zkteco-home/redis-windows#56]
Can you make it so that when a redis crashes, it doesn't stop but keeps running? Because otherwise the database is unstable, stops responding, and unsnapshotted data is lost. What to do?

**Comment by zkteco-home** [comment]
ok,thanks for your suggestion,I will try to do it,at best you can send me your error report.sometimes crash,it means memory is error,code cant continue to run.

**Comment by zkteco-home** [comment]
stop-writes-on-bgsave-error no

try to use this config
