### ISSUE TITLE
Redis tairgis.dll

### ISSUE THREAD

**Issue by adminpass** [zkteco-home/redis-windows#58]
https://github.com/tair-opensource/TairGis

**TairGis** is a Redis Module that supports the query of intersection, contains, and within relationships between points, lines, and polygons. It has the following features:

- Fast query performance
- Use `RTree` storage
- The function of Redis `GEORADIUS` [command](https://redis.io/commands/georadius) can be realized through `GIS.SEARCH`

Could you please compile tairgis module on windows?

**Comment by zkteco-home** [comment]
I am not sure if I can compile it,i will try to do it

**Comment by zkteco-home** [comment]
https://github.com/zkteco-home/TairGis

try to test it
![image](https://github.com/zkteco-home/redis-windows/assets/66519168/d9a9165f-0785-4c35-9945-be44e8cc0c24)
