### ISSUE TITLE
crash with cluster mode  errorcode c0000005

### ISSUE THREAD

**Issue by KnightBlood** [zkteco-home/redis-windows#6]
![IMG_20211230_171503](https://user-images.githubusercontent.com/14256591/147738124-7734d555-80be-4a97-92a8-67d8b50903d9.jpg)
node config like this
port from 6380-6385

**Comment by KnightBlood** [comment]
need exce redis-cli --cluster create IP:6380 IP:6381 IP:6382 IP:6383 IP:6384 IP:6385 --cluster-replicas 1

**Comment by zkteco-home** [comment]
> need exce redis-cli --cluster create IP:6380 IP:6381 IP:6382 IP:6383 IP:6384 IP:6385 --cluster-replicas 1

in fact i already tested this cluster function before released.maybe something happend.can you send me your all config files,i will test it again.thank you very much

**Comment by KnightBlood** [comment]
> > need exce redis-cli --cluster create IP:6380 IP:6381 IP:6382 IP:6383 IP:6384 IP:6385 --cluster-replicas 1
> 
> in fact i already tested this cluster function before released.maybe something happend.can you send me your all config files,i will test it again.thank you very much,you can send config file to my email : [my9988@126.com](mailto:my9988@126.com)

i had send all file to your email

**Comment by zkteco-home** [comment]
I fixed this issue,it took me long time to locate issue,because that there is a little difficult about this issue. i tested it like this,you test it please and tell me result.
![image](https://user-images.githubusercontent.com/66519168/148535544-c7c921f3-e746-46f2-97b0-7ade490c1095.png)

**Comment by KnightBlood** [comment]
I need quite a long time to test its stability, performance, efficiency

**Comment by zkteco-home** [comment]
i updated program,please pull new and test it.you can refer to #5 issue,for old version when key number is large,it will stop work.
