### ISSUE TITLE
No command prompt

### ISSUE THREAD

**Issue by XiuMu02** [zkteco-home/redis-windows#62]
Why is there no command prompt? The Linux version always has a prompt after entering commands.

**Comment by zkteco-home** [comment]
please send your screenshot here,i will check it

**Comment by zkteco-home** [comment]
![image](https://github.com/zkteco-home/redis-windows/assets/66519168/6a8d0ba9-a51a-429d-ac52-16dbbb7d9354)

**Comment by zkteco-home** [comment]
just now i checked,there is command tips .

**Comment by XiuMu02** [comment]
I found that there is a command prompt when I directly start redis-server.exe.
But if I run it as a Windows service, set a password, and use the "auth" command to verify the password, there is no command prompt. I have to enter the "help" command or enter the password using "-a" option to see the command prompt.
![no](https://github.com/zkteco-home/redis-windows/assets/92033966/055fc491-4a25-43ce-85b1-9fb9f1e152ee)
![yes1](https://github.com/zkteco-home/redis-windows/assets/92033966/0348fe03-9aab-4e3e-ab64-56d18e943e80)
![yes2](https://github.com/zkteco-home/redis-windows/assets/92033966/66d29727-fa7d-4989-868d-216369b9d12a)
I'm not sure if it's a bug, but it doesn't have a significant impact anyway. Thank you for your response.

**Comment by zkteco-home** [comment]
Thanks for your feedback,I will continue to investigate it.
