### ISSUE TITLE
Exception code: 0xc0000005

### ISSUE THREAD

**Issue by 1doman** [zkteco-home/redis-windows#67]
occurs occasionally- sometimes every 30 mins

Faulting application name: redis-server.exe, version: 7.2.4.0, time stamp: 0x65a2a9d1
Faulting module name: redis-server.exe, version: 7.2.4.0, time stamp: 0x65a2a9d1
Exception code: 0xc0000005
Fault offset: 0x000000000009b473
Faulting process id: 0x11ec
Faulting application start time: 0x01da5521d1bb170f
Faulting application path: C:\Helix\redis\redis-server.exe
Faulting module path: C:\Helix\redis\redis-server.exe
Report Id: 062c324e-941e-4b1e-8d34-9be224dfe5ec
Faulting package full name: 
Faulting package-relative application ID: 

using v7.2.4

======================

Fault bucket 1364912646671317876, type 4
Event Name: APPCRASH
Response: Not available
Cab Id: 0

Problem signature:
P1: redis-server.exe
P2: 7.2.4.0
P3: 65a2a9d1
P4: redis-server.exe
P5: 7.2.4.0
P6: 65a2a9d1
P7: c0000005
P8: 000000000009b473
P9: 
P10: 

Attached files:
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER.25369844-da38-449f-9975-c5394d030293.tmp.dmp
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER.8c71ecc7-c194-4402-88eb-92806c960b9e.tmp.WERInternalMetadata.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER.264aecb2-9e44-463a-ac39-017d63f93d00.tmp.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER.2e85b1f9-fd7b-4718-947e-b057718e5dcb.tmp.csv
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER.aa6ffd07-9427-407f-93c0-e21356d04622.tmp.txt

These files may be available here:
\\?\C:\ProgramData\Microsoft\Windows\WER\ReportArchive\AppCrash_redis-server.exe_cd9f66c5208b52db4e06c97966c35880c572a3_de7a47c7_2e95ca83-e2ad-4304-8ed6-60047fbccf58

Analysis symbol: 
Rechecking for solution: 0
Report Id: 33375c2c-496e-46a5-bce5-4b718807af5a
Report Status: 268435456
Hashed bucket: 51d9beca71e2b59ce2f124d20e483b74
Cab Guid: 0

**Comment by 1doman** [comment]
App crash report archive file:

Version=1
EventType=APPCRASH
EventTime=133512777143474423
ReportType=2
Consent=1
UploadTime=133512777148630812
ReportStatus=268435456
ReportIdentifier=2e95ca83-e2ad-4304-8ed6-60047fbccf58
IntegratorReportIdentifier=33375c2c-496e-46a5-bce5-4b718807af5a
Wow64Host=34404
NsAppName=redis-server.exe
AppSessionGuid=000020cc-0000-0022-d9e4-62292355da01
TargetAppId=W:00060a9dc0a9d9f2f7f08cbd7c832251d05700000900!0000d987b7f9c62b3d6f3c05122dec693ca108f94e1c!redis-server.exe
TargetAppVer=2024//01//13:15:18:41!0!redis-server.exe
BootId=4294967295
ServiceSplit=3279017472
TargetAsId=148752
IsFatal=1
EtwNonCollectReason=1
Response.BucketId=51d9beca71e2b59ce2f124d20e483b74
Response.BucketTable=4
Response.LegacyBucketId=1364912646671317876
Response.type=4
Sig[0].Name=Application Name
Sig[0].Value=redis-server.exe
Sig[1].Name=Application Version
Sig[1].Value=7.2.4.0
Sig[2].Name=Application Timestamp
Sig[2].Value=65a2a9d1
Sig[3].Name=Fault Module Name
Sig[3].Value=redis-server.exe
Sig[4].Name=Fault Module Version
Sig[4].Value=7.2.4.0
Sig[5].Name=Fault Module Timestamp
Sig[5].Value=65a2a9d1
Sig[6].Name=Exception Code
Sig[6].Value=c0000005
Sig[7].Name=Exception Offset
Sig[7].Value=000000000009b473
DynamicSig[1].Name=OS Version
DynamicSig[1].Value=10.0.20348.2.0.0.272.7
DynamicSig[2].Name=Locale ID
DynamicSig[2].Value=1033
DynamicSig[22].Name=Additional Information 1
DynamicSig[22].Value=97e1
DynamicSig[23].Name=Additional Information 2
DynamicSig[23].Value=97e1b0f0dc4e60c8ae4a0f84b193ae6b
DynamicSig[24].Name=Additional Information 3
DynamicSig[24].Value=da02
DynamicSig[25].Name=Additional Information 4
DynamicSig[25].Value=da0226c569d1c01d708b295bd40c590f
UI[2]=C:\Helix\redis\redis-server.exe
UI[5]=Close
UI[8]=Redis for Windows stopped working and was closed
UI[9]=A problem caused the application to stop working correctly. Windows will notify you if a solution is available.
UI[10]=&Close
LoadedModule[0]=C:\Helix\redis\redis-server.exe
LoadedModule[1]=C:\Windows\SYSTEM32\ntd1l.dll
LoadedModule[2]=C:\Windows\System32\kern3l32.dll
LoadedModule[3]=C:\Windows\SYSTEM32\ntdll.dll
LoadedModule[4]=C:\Windows\System32\KERNEL32.DLL
LoadedModule[5]=C:\Windows\System32\KERNELBASE.dll
LoadedModule[6]=C:\Program Files\SentinelOne\Sentinel Agent 22.2.5.806\InProcessClient64.dll
LoadedModule[7]=C:\Windows\System32\ADVAPI32.dll
LoadedModule[8]=C:\Windows\System32\msvcrt.dll
LoadedModule[9]=C:\Windows\System32\sechost.dll
LoadedModule[10]=C:\Windows\System32\bcrypt.dll
LoadedModule[11]=C:\Windows\System32\RPCRT4.dll
LoadedModule[12]=C:\Windows\System32\SHLWAPI.dll
LoadedModule[13]=C:\Windows\SYSTEM32\dbghelp.dll
LoadedModule[14]=C:\Windows\System32\ucrtbase.dll
LoadedModule[15]=C:\Windows\System32\PSAPI.DLL
LoadedModule[16]=C:\Windows\System32\USER32.dll
LoadedModule[17]=C:\Windows\System32\win32u.dll
LoadedModule[18]=C:\Windows\System32\GDI32.dll
LoadedModule[19]=C:\Windows\System32\gdi32full.dll
LoadedModule[20]=C:\Windows\System32\msvcp_win.dll
LoadedModule[21]=C:\Windows\System32\SHELL32.dll
LoadedModule[22]=C:\Windows\SYSTEM32\VERSION.dll
LoadedModule[23]=C:\Windows\System32\ws2_32.dll
LoadedModule[24]=C:\Windows\System32\bcryptPrimitives.dll
LoadedModule[25]=C:\Windows\SYSTEM32\CRYPTBASE.DLL
LoadedModule[26]=C:\Windows\system32\mswsock.dll
LoadedModule[27]=C:\Windows\SYSTEM32\kernel.appcore.dll
State[0].Key=Transport.DoneStage1
State[0].Value=1
OsInfo[0].Key=vermaj
OsInfo[0].Value=10
OsInfo[1].Key=vermin
OsInfo[1].Value=0
OsInfo[2].Key=verbld
OsInfo[2].Value=20348
OsInfo[3].Key=ubr
OsInfo[3].Value=2227
OsInfo[4].Key=versp
OsInfo[4].Value=0
OsInfo[5].Key=arch
OsInfo[5].Value=9
OsInfo[6].Key=lcid
OsInfo[6].Value=1033
OsInfo[7].Key=geoid
OsInfo[7].Value=244
OsInfo[8].Key=sku
OsInfo[8].Value=7
OsInfo[9].Key=domain
OsInfo[9].Value=1
OsInfo[10].Key=prodsuite
OsInfo[10].Value=272
OsInfo[11].Key=ntprodtype
OsInfo[11].Value=3
OsInfo[12].Key=platid
OsInfo[12].Value=10
OsInfo[13].Key=sr
OsInfo[13].Value=0
OsInfo[14].Key=tmsi
OsInfo[14].Value=222518461
OsInfo[15].Key=osinsty
OsInfo[15].Value=2
OsInfo[16].Key=iever
OsInfo[16].Value=11.1.20348.0-11.0.1000
OsInfo[17].Key=portos
OsInfo[17].Value=0
OsInfo[18].Key=ram
OsInfo[18].Value=8192
OsInfo[19].Key=svolsz
OsInfo[19].Value=119
OsInfo[20].Key=wimbt
OsInfo[20].Value=0
OsInfo[21].Key=blddt
OsInfo[21].Value=210507
OsInfo[22].Key=bldtm
OsInfo[22].Value=1500
OsInfo[23].Key=bldbrch
OsInfo[23].Value=fe_release
OsInfo[24].Key=bldchk
OsInfo[24].Value=0
OsInfo[25].Key=wpvermaj
OsInfo[25].Value=0
OsInfo[26].Key=wpvermin
OsInfo[26].Value=0
OsInfo[27].Key=wpbuildmaj
OsInfo[27].Value=0
OsInfo[28].Key=wpbuildmin
OsInfo[28].Value=0
OsInfo[29].Key=osver
OsInfo[29].Value=10.0.20348.2227.amd64fre.fe_release.210507-1500
OsInfo[30].Key=buildflightid
OsInfo[31].Key=edition
OsInfo[31].Value=ServerStandard
OsInfo[32].Key=ring
OsInfo[32].Value=Retail
OsInfo[33].Key=expid
OsInfo[34].Key=fconid
OsInfo[34].Value=19193644,0,2,0;35681102,0,1,0
OsInfo[35].Key=containerid
OsInfo[36].Key=containertype
OsInfo[37].Key=edu
OsInfo[37].Value=0
OsInfo[38].Key=servicinginprogress
OsInfo[38].Value=0
FriendlyEventName=Stopped working
ConsentKey=APPCRASH
AppName=Redis for Windows
AppPath=C:\Helix\redis\redis-server.exe
NsPartner=windows
NsGroup=windows8
ApplicationIdentity=BDA7C2058D8808CB5E0A834CA962335C
MetadataHash=74378190

**Comment by zkteco-home** [comment]
It's my first time to get this issue report,please send your config here
