### ISSUE TITLE
经常挂了

### ISSUE THREAD

**Issue by 3400442579** [zkteco-home/redis-windows#69]
=== REDIS BUG REPORT START: Cut & paste starting from here ===
[009852] 29 Feb 08:35:44.642 # --- EXCEPTION_ACCESS_VIOLATION
[009852] 29 Feb 08:35:44.642 # --- STACK TRACE
redis-server.exe!((null):0)(0x1401F1F50, 0x0014FF60, 0x0014EAA0, 0x0014EAA0)
redis-server.exe!((null):0)(0x0014EAA0, 0x0014FF01, 0x140125990, 0x7FFC5E899880)
KERNELBASE.dll!UnhandledExceptionFilter((null):0)(0x00000000, 0x7FFC5E9833D4, 0x00000000, 0x00000000)
ntdll.dll!memset((null):0)(0x00000000, 0x00000000, 0x0014F730, 0x0014F068)
ntdll.dll!_C_specific_handler((null):0)(0x00000000, 0x0014F050, 0x00000000, 0x140000000)
ntdll.dll!_chkstk((null):0)(0x0014F050, 0x00000000, 0x7FFC5D1CBC3C, 0x7FFC5D120000)
ntdll.dll!RtlWalkFrameChain((null):0)(0x0014F490, 0x7FFC5E8700E1, 0x00000000, 0x7FFC5E8701F5)
ntdll.dll!KiUserExceptionDispatcher((null):0)(0xE5155488166, 0x0014F9B0, 0x7FE1088002A0, 0x00000000)
redis-server.exe!KiUserExceptionDispatcher((null):0)(0x1DA6AA73B377AC9, 0x7FE11C400A80, 0x0014FA20, 0x140146049)
redis-server.exe!KiUserExceptionDispatcher((null):0)(0x0001693D, 0x7FE1088002A0, 0x00000000, 0x004C14E0)
redis-server.exe!KiUserExceptionDispatcher((null):0)(0x7FE1074000F0, 0x14009C456, 0x6127A7098E5C0, 0x0000001B)
redis-server.exe!KiUserExceptionDispatcher((null):0)(0x7FE1088002A0, 0x00000000, 0x00000000, 0x1401EB2C0)
redis-server.exe!KiUserExceptionDispatcher((null):0)(0x00000000, 0xFFFFFFFF0000001B, 0x00000001, 0x190000000000)
redis-server.exe!KiUserExceptionDispatcher((null):0)(0x0000267C, 0x1401EB628, 0x1401CBF54, 0x7FE106401500)
redis-server.exe!KiUserExceptionDispatcher((null):0)(0x00000000, 0x00000000, 0x00000001, 0x004C21D0)
redis-server.exe!KiUserExceptionDispatcher((null):0)(0x00000000, 0x14012B805, 0x004C14E0, 0x00000000)
redis-server.exe!KiUserExceptionDispatcher((null):0)(0x00000000, 0x00000000, 0x00000000, 0x00000000)
KERNEL32.DLL!BaseThreadInitThunk((null):0)(0x00000000, 0x00000000, 0x00000000, 0x00000000)
ntdll.dll!RtlUserThreadStart((null):0)(0x00000000, 0x00000000, 0x00000000, 0x00000000)
ntdll.dll!RtlUserThreadStart((null):0)(0x00000000, 0x00000000, 0x00000000, 0x00000000)
[009852] 29 Feb 08:35:44.689 #
=== REDIS BUG REPORT END. Make sure to include from START to END. ===

![image](https://github.com/zkteco-home/redis-windows/assets/34226979/2ee91ad3-38c6-4754-acf7-b7d7bc532749)

save 3600 1 300 100 60 10000

port 6379 
requirepass xxxxxxxxxxxxxxxxxx
maxmemory 256mb
appendonly no
maxmemory-policy allkeys-lru
rdbchecksum no
protected-mode no
maxmemory-clients 50%

**Comment by zkteco-home** [comment]
I use redis-benchmark.ext with your config and tested half day,it is ok,please try to use redis-benchmark.exe to test it.if there is issue about redis,many user will report error

**Comment by 3400442579** [comment]
![image](https://github.com/zkteco-home/redis-windows/assets/34226979/0dee7471-a535-456d-973f-b7dfd95389dd)

**Comment by zkteco-home** [comment]
use redis-benchmark.exe to test it?
