### ISSUE TITLE
The redis-cli terminal crashes after entering the subscribe command.

### ISSUE THREAD

**Issue by ASTK007** [zkteco-home/redis-windows#70]
The problematic version is 7.2.4. When I use 7.2.3 the problem disappears and the terminal does not crash.
And No log output on the server terminal.

**Comment by zkteco-home** [comment]
thanks for your feedback,please tell me how to reproduce this issue when you use redis-cli terminal?I will check it according to your command

**Comment by ASTK007** [comment]
> thanks for your feedback, how to reproduce this issue when you use redis-cli terminal?I will check it according to your command

1. Click redis-server to run the server
2. Click redis-cli to open a new terminal window and enter subscribe xxxxxx (xxxxxx can be anything)
3. After pressing Enter, the window will output the subscription information and close quickly

**Comment by zkteco-home** [comment]
This issue fixed,  next version is coming soon,thanks
