### ISSUE TITLE
redis-benchmark.exe  :  ERR unknown command 'ZPOPMIN'nan(ind) (overall: -nan(ind))

### ISSUE THREAD

**Issue by 3400442579** [zkteco-home/redis-windows#71]
====== PING_INLINE ======
  100000 requests completed in 4.62 seconds
  50 parallel clients
  3 bytes payload
  keep alive: 1
  host configuration "save": jd 900 jd 300 jd 60
  host configuration "appendonly": no
  multi-thread: no

99.975% <= 9.103 milliseconds (cumulative count 99975)
100.000% <= 10.103 milliseconds (cumulative count 100000)

Summary:
  throughput summary: 21321.96 requests per second
  latency summary (msec):
          avg       min       p50       p95       p99       max
        1.805     0.616     1.671     3.111     3.727     9.887
**Error from server: ERR unknown command 'ZPOPMIN'nan(ind) (overall: -nan(ind))**

**Comment by zkteco-home** [comment]
working fine
![image](https://github.com/zkteco-home/redis-windows/assets/66519168/d0b30a9a-55a8-4273-99f3-173e7b2541ff)
