### ISSUE TITLE
Unable to execute flushdb command

### ISSUE THREAD

**Issue by DreamPlaceToStart** [zkteco-home/redis-windows#74]
<img width="391" alt="redis flushdb" src="https://github.com/zkteco-home/redis-windows/assets/11283799/a3134c07-06f4-4c42-952f-c4f84c6d149f">

**Comment by zkteco-home** [comment]
need to add sync or async

**Comment by DreamPlaceToStart** [comment]
Use the default values and do not need to display the specified sync or async . 
<img width="234" alt="test" src="https://github.com/zkteco-home/redis-windows/assets/11283799/aca8304f-3d12-4d37-8f27-8c1b37dcbf87">
