### ISSUE TITLE
Redis 7.4

### ISSUE THREAD

**Issue by AnalistaProgramadorWebBjr** [zkteco-home/redis-windows#79]
Hello, first, thank you very much for this great development. Likewise, I am having problems with the new version of Redis, since apparently this new version executes additional commands from time to time when I have nothing running in Redis or saving data in Redis other than the REDIS INSIGHT client.
This does not happen in version 7.2.5 even if you have several clients executing commands

![Redis 7 2 5](https://github.com/user-attachments/assets/d21ec4e8-e1ee-4b94-9026-de7620bca59c)

vs. version 7.4 only with 2 clients and already thousands of commands.

![Redis7 4](https://github.com/user-attachments/assets/98848c5d-bd56-4a0c-b42f-18888416ea72)

**Comment by zkteco-home** [comment]
I checked your message,but i didnt get it,what is additional commands?how can i reproduce issue?

**Comment by AnalistaProgramadorWebBjr** [comment]
What I do is use Redis Insight monitor and use Redis version 7.4 
My configuration is:

save ""
port 6379
bind 127.0.0.1
requirepass '000000'
maxmemory 512mb
maxmemory-policy allkeys-lru
appendonly no
rdbchecksum no
protected-mode yes
loglevel notice
logfile "c:/Redis/redis.log"
databases 16
tcp-backlog 511
tcp-keepalive 300
timeout 0
tcp-backlog 511
client-query-buffer-limit 1gb
latency-monitor-threshold 0
lua-time-limit 5000

Then I turn on the service installed on Windows and when I run a refresh on the insight monitor it seems that the commands per second that are executed never close, which does happen in previous versions.

This is an image without using any queue, just lying open insight, just refreshing in redis 7.4
![image](https://github.com/user-attachments/assets/62452af3-ef72-423a-9529-07059cedfe22)

**Comment by zkteco-home** [comment]
I used redis-cli.exe to test it, type info command and observe  
![image](https://github.com/user-attachments/assets/c8f8baf2-4bbe-4d3a-b606-e8361ea98f18)

I also used 3rd tools and observe 
![image](https://github.com/user-attachments/assets/3af395d7-41f7-479a-a067-2081e1978270)
I didnt get your result

i think maybe bcz of your insight tool ,it sent commands

code is as same as official ,it is impossible to create commands if nothing to do
