### ISSUE TITLE
win11设置自动启动服务报错

### ISSUE THREAD

**Issue by ren-si-yu** [zkteco-home/redis-windows#81]
PS D:\scoop\apps\redis\current> sc.exe create Redis binpath=D:\scoop\apps\redis\current\redis-server.exe start= auto
[SC] CreateService 成功

PS D:\scoop\apps\redis\current> net start Redis
服务没有响应控制功能。

请键入 NET HELPMSG 2186 以获得更多的帮助。

PS D:\scoop\apps\redis\current> NET HELPMSG 2186

服务没有响应控制功能。

**Comment by zkteco-home** [comment]
try to use install_redis.cmd

@echo on
cd /d %~dp0
sc create redis binPath= "\"%CD%\redis-server.exe\" --service-run \"%CD%\redis.conf\"" DisplayName= "Redis" start= auto depend= TCPIP
sc description redis "Redis Cache Service"
net start redis
