### ISSUE TITLE
use redis-cli(ver: 3.2.100) to register lua function, then make redis-server crash！

### ISSUE THREAD

**Issue by Json-bit** [zkteco-home/redis-windows#82]
use redis-cli(ver: 3.2.100) to register lua function, then make redis-server(ver:7.0.10) crash！
![redis  bug1](https://github.com/user-attachments/assets/be1ec29d-288b-4a48-ba33-9bdd8978b56b)
![redis bug](https://github.com/user-attachments/assets/c796c028-c096-4943-80cb-23eb19998903)

use redis-cli(ver: 7.0.10) to register lua function，get failed！
![redis bug2](https://github.com/user-attachments/assets/8696afe1-114c-4416-847b-6186990fb4d8)

How to register lua function in windows，I tried all methods，but no work！

**Comment by Json-bit** [comment]
use redis-cli(ver: 7.0.10) to input like this，It doesn't work，but It works in redis-cli(ver: 3.2.100)

![redis bug3](https://github.com/user-attachments/assets/b5e1d891-f69e-429d-b602-84cb6f925000)

![image](https://github.com/user-attachments/assets/6903c59b-73fd-4cc8-934a-16330a8e2756)

two case is in redis-server(ver:7.0.10) . why？

**Comment by zkteco-home** [comment]
![image](https://github.com/user-attachments/assets/e42ec3c0-c3b3-462f-baff-c90511d274cf)
I tested it with 7.4.0,It works fine.
